name: Backup Project 
on: [push]

jobs:
  Backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Main
        run: |
          echo "hello from cicd"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          git diff --name-only
