name: Workflow for Branch 2

on:
  push:
    branches:
      - "02-02-2024-test"
    paths:
      - ".github/workflows/myworkflow.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy your application
        run: |
         echo "my test"
         echo "hello !"
