name: Backup Project 
on: 
  push:
   branches:
     - 02-02-2024-test

env:
  USER: 'Jihed'

jobs:
  Backup:
    runs-on: ubuntu-latest
    steps:
      - name: clone Project
        run: |
          echo "hello test branch"
